export default [
	'Com certeza!',
	'Eu não recomendo.',
	'Seria ideal.',
	'Hoje é não, faro.',
	'Talvez...',
	'Tenta a sorte',
	'Se nem você sabe, quem dirá eu.',
	'Sim!',
	'Não!',
	'De jeito nenhum',
	'E eu é que tenho que saber?',
	'Não sou capaz de opinar..',
	'Você tá querendo polêmica???',
	'Sei de nada',
	'Jamais',
	'Sim, mas eu não disse nada. Viu?',
	'Sem sombra de dúvidas.',
	'Ainda não sei responder sobre isso.',
	'Deixa de baitolagem',
	'Em casa de ferreiro o espeto é de pau. Então, vai que é tua.',
	'Você já sabe a resposta.'
]